// Package manifest parses and persists the multiversa.toml declarative manifest.
package manifest

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

const DefaultPath = "multiversa.toml"

type Manifest struct {
	Multiversa Meta              `toml:"multiversa"`
	Stack      map[string]string `toml:"stack"`
	Agents     Agents            `toml:"agents"`
	Backend    Backend           `toml:"backend"`
	Credits    Credits           `toml:"credits"`
}

type Meta struct {
	Profile string `toml:"profile"`
	Ethic   string `toml:"ethic"`
	Version string `toml:"version"`
}

type Agents struct {
	Enabled []string `toml:"enabled"`
}

type Backend struct {
	Provider string `toml:"provider"`
	URL      string `toml:"url,omitempty"`
	AnonKey  string `toml:"anon_key,omitempty"`
}

type Credits struct {
	AutoPrint bool `toml:"auto_print"`
}

func Default() *Manifest {
	return &Manifest{
		Multiversa: Meta{
			Profile: "personal-os",
			Ethic:   "human-in-the-loop",
			Version: "0.1",
		},
		Stack:   map[string]string{},
		Agents:  Agents{Enabled: []string{}},
		Backend: Backend{Provider: "local"},
		Credits: Credits{AutoPrint: true},
	}
}

func Load(path string) (*Manifest, error) {
	m := &Manifest{}
	if _, err := toml.DecodeFile(path, m); err != nil {
		return nil, fmt.Errorf("read manifest %s: %w", path, err)
	}
	return m, nil
}

func Save(path string, m *Manifest) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer f.Close()
	if _, err := f.WriteString("# multiversa.toml — generated by `multiversa init`\n"); err != nil {
		return err
	}
	enc := toml.NewEncoder(f)
	enc.Indent = ""
	return enc.Encode(m)
}

func (m *Manifest) Validate() error {
	if m.Multiversa.Ethic != "" && m.Multiversa.Ethic != "human-in-the-loop" {
		return fmt.Errorf("ethic must be 'human-in-the-loop' — Multiversa is built on that contract")
	}
	switch m.Backend.Provider {
	case "", "local", "supabase", "firebase", "insforge":
	default:
		return fmt.Errorf("unknown backend provider %q (allowed: local, supabase, firebase, insforge)", m.Backend.Provider)
	}
	return nil
}
